/*
 * Copyright (c) Mike Lischke. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */

import { type ComponentChild, type VNode } from "preact";

import type { ISbDmNoteEvent, ISbDmTrackMeasure } from "../../../core/ScoreBookDataModel.js";
import {
    Damping, ExcitationMode, HandTechnique, NoteDisplayType, StickTechnique,
    type INoteArticulation,
} from "../../../core/ScoreBookDataModel.js";
import type { IFraction, IAudioData, ISubdivision } from "../../../core/types/general.js";
import type { IScoreMetrics } from "../../../player/TimeCoordinator.js";
import { NoteImage, NoteImageHeadType, NoteKind, NoteLength } from "../framework/NoteImage.js";
import { UIComponent, type ICommonUIProperties } from "../framework/UIComponent.js";

export interface IStaffNoteViewerProperties extends ICommonUIProperties {
    isLastBar: boolean;
    timeSignature: string;
    scoreMetrics: IScoreMetrics;
    baseSteps: number;

    measure: ISbDmTrackMeasure;

    /** Maximum noteLine value across all variants of the instrument (default 1 = single line). */
    maxNoteLine?: number;
}

interface IStaffStepNode {
    type: "step";

    /** 0-based index into the measure's steps array. */
    stepIndex: number;

    /** Defined when this step has a sounding note; undefined for rests / empty slots. */
    glyph?: INoteGlyph;

    /** Number of beam strokes (0 = not beamable). Derived from glyph icon. */
    beamCount: number;

    displayType: NoteDisplayType;

    diamondOpen?: boolean;

    /** Duration in base-grid steps (for beam extent and occupied-step calculation). */
    lengthSteps: number;

    /** The staff line this note sits on (1-based, counting from the top). Undefined for rests / empty slots. */
    noteLine?: number;

    /** The note style for this step, if it has a sounding note. Carries characteristics for decoration. */
    noteStyle?: IAudioData;

    /** The per-note articulation (damping, accent, ghost) for this step. */
    articulation?: INoteArticulation;
}

interface IStaffSubdivisionNode {
    type: "subdivision";
    subdivision: ISubdivision;
    children: IStaffTreeNode[];
}

type IStaffTreeNode = IStaffStepNode | IStaffSubdivisionNode;

interface INoteGlyph {
    icon: NoteLength;
    dotted: boolean;
}

interface IBeamInfo {
    segments: IBeamSegment[];
}

interface IBeamSegment {
    /** 1-based beam level: 1 = eighth, 2 = sixteenth, 3 = thirty-second. */
    level: number;

    kind: "shared-right" | "partial-left" | "partial-right";

    /** Slot widths from this notehead to the next beam member (shared beams only). */
    extentSteps?: number;
}

interface ITupletLabel {
    leftPercent: number;
    widthPercent: number;
    text: string;
    bracket: boolean;
    placement: "above" | "below";
}

interface IRestGroup {
    startStep: number;
    lengthSteps: number;
    icon: NoteLength;
    dotted: boolean;
}

interface IRestCandidate {
    steps: number;
    alignmentSteps: number;
    icon: NoteLength;
    dotted: boolean;
}

export class StaffNoteViewer extends UIComponent<IStaffNoteViewerProperties> {
    public override render(): ComponentChild {
        const { isLastBar, timeSignature, scoreMetrics, baseSteps, measure, maxNoteLine = 1 } = this.props;
        const [beatsPerBarStr, beatUnitStr] = timeSignature.split("/");
        const className = this.generateFinalClassName([
            "staff-note-viewer",
            this.classFromProperty(isLastBar, "last-bar"),
        ]);

        const { stepsPerBar, stepsPerPulse } = scoreMetrics;

        // Build an array of sounding events indexed by visible step position.
        // Sounding steps and sounding events are in 1:1 correspondence and in
        // the same order (both generated by createSerializedEventsFromMeasure).
        // Non-grid-slot rest events (noteStyle === undefined) may be interleaved
        // and must be skipped to avoid shifting all subsequent assignments.
        const eventsByStep = new Array<ISbDmNoteEvent | undefined>(measure.steps.length);
        let ei = 0;
        for (let si = 0; si < measure.steps.length && ei < measure.events.length; si++) {
            if (measure.steps[si].noteStyleId !== undefined) {
                while (ei < measure.events.length && measure.events[ei].audioData === undefined) {
                    ei++;
                }

                if (ei < measure.events.length) {
                    eventsByStep[si] = measure.events[ei];
                    ei++;
                }
            }
        }

        const { nodes } = this.buildTree(eventsByStep, undefined, 0, 0, measure.steps.length);

        // Step indices that are "occupied" by the tail of a preceding note's duration.
        const noteOccupied = this.computeNoteOccupiedSteps(nodes);

        // Beam span map (keyed by stepIndex).
        const beamSpans = new Map<number, IBeamInfo>();
        this.computeBeamSpansForLevel(nodes, noteOccupied, stepsPerPulse, true, beamSpans, 1);

        // Tuplet bracket/number labels positioned by flex percentage.
        const tupletLabels = this.computeTupletLabels(nodes, beamSpans, baseSteps);

        // Rest groups for top-level steps only (subdivision steps render as single rests).
        const beatsPerBarValue = Number(beatsPerBarStr);
        const beatUnitValue = Number(beatUnitStr);
        const stepResolution = beatsPerBarValue > 0 ? (stepsPerBar * beatUnitValue) / beatsPerBarValue : 0;
        const restGroups = Number.isFinite(stepResolution) && stepResolution > 0
            ? this.computeRestGroups(nodes, noteOccupied, stepsPerBar, stepsPerPulse, stepResolution)
            : new Map<number, IRestGroup>();

        // Combine note tails and rest group tails into one "render-empty" set.
        const allOccupied = new Set<number>(noteOccupied);
        for (const [startIdx, group] of restGroups) {
            for (let j = 1; j < group.lengthSteps; j++) {
                allOccupied.add(startIdx + j);
            }
        }

        const hasAnyNote = nodes.some((n) => {
            return this.nodeHasAnyNote(n);
        });

        const centerLine = (maxNoteLine + 1) / 2;

        // Whole and half rests sit on the centre line (odd count) or the line just below it (even count).
        const restNoteLine = Math.ceil(centerLine);
        const restLineOffset = (restNoteLine - centerLine) * 10;

        const runs =
            hasAnyNote
                ? this.renderItems(nodes, allOccupied, restGroups, beamSpans, eventsByStep, "", false,
                    undefined, centerLine, restLineOffset)
                : [this.renderWholeBarRestSlot(restLineOffset)];

        // Render staff lines. For a single line, render the centred middle line as before.
        // For multiple lines, render N lines symmetrically around the vertical centre.
        const staffLines: ComponentChild[] = [];
        for (let i = 1; i <= maxNoteLine; i++) {
            const offset = ((i - centerLine) * 10) + 31.5; // 10px = line spacing, +16px = prefix-row shift
            staffLines.push(
                <div
                    key={`staff-line-${i}`}
                    className="staff-note-viewer-line"
                    style={{ top: `calc(50% + ${offset}px)` }}
                />,
            );
        }

        return (
            <div className={className} aria-hidden {...this.dataAttributes}>
                {staffLines}
                <div className="staff-note-viewer-runs">
                    {runs}
                </div>
                {tupletLabels.length > 0
                    ? (
                        <div className="staff-note-viewer-tuplets">
                            {tupletLabels.map((label) => {
                                const baseCls = label.bracket
                                    ? "staff-note-viewer-tuplet-bracket"
                                    : "staff-note-viewer-tuplet-number";
                                const placementCls = label.placement === "below"
                                    ? "staff-note-viewer-tuplet-below"
                                    : "staff-note-viewer-tuplet-above";
                                const style = label.bracket
                                    ? { left: `${label.leftPercent}%`, width: `${label.widthPercent}%` }
                                    : { left: `${label.leftPercent + (label.widthPercent / 2)}%` };

                                return (
                                    <span
                                        key={`${label.leftPercent}-${label.text}-${label.placement}`}
                                        className={`${baseCls} ${placementCls}`}
                                        style={style}
                                    >
                                        <span className="staff-note-viewer-tuplet-text">{label.text}</span>
                                    </span>
                                );
                            })}
                        </div>
                    )
                    : null}
                {isLastBar ? <div className="staff-note-viewer-final-barline" /> : null}
            </div>
        );
    }

    /**
     * Recursively builds the render tree from measure steps and subdivisions. Mirrors
     * GridMeasureRow.buildLevel but enriches each step node with glyph and beam data.
     *
     * @param eventsByStep Array of sounding note events indexed by visible step position.
     *                     Undefined entries represent rests (no sounding note at that step).
     * @param parentSubdivisionId The ID of the parent subdivision, if any.
     * @param tupletDepth The nesting depth of tuplets at this level (0 for top level, increases by 1 for each
     *                    nested tuplet). Non-tuplet subdivisions do not increase this depth.
     * @param startIdx The starting step index for this level of the tree (inclusive).
     * @param endIdx The ending step index for this level of the tree (exclusive).
     *
     * @returns An object containing the list of tree nodes and the total length in steps covered by this subtree.
     */
    private buildTree(eventsByStep: Array<ISbDmNoteEvent | undefined>,
        parentSubdivisionId: number | undefined,
        tupletDepth: number, startIdx: number, endIdx: number): { nodes: IStaffTreeNode[]; length: number; } {
        const { measure, scoreMetrics } = this.props;

        const childSubdivisions = measure.subdivisions.filter((s) => {
            // Normalize null → undefined: JSON round-trips convert undefined array elements to null.
            return (s.parentSubdivisionId ?? undefined) === parentSubdivisionId;
        });

        const nodes: IStaffTreeNode[] = [];
        let i = startIdx;

        while (i < endIdx) {
            const start = i;
            const subdivision = childSubdivisions.find((s) => {
                return s.startStep === start;
            });

            if (subdivision) {
                // Track subdivision nesting depth for beam count — each level
                // of subdivision (tuplet or not) halves the effective note duration,
                // adding one beam level. The isTuplet flag controls tuplet bracket
                // display only, not beam depth.
                const nextTupletDepth = tupletDepth + 1;
                const { nodes: children, length } = this.buildTree(eventsByStep, subdivision.id,
                    nextTupletDepth, subdivision.startStep,
                    subdivision.startStep + subdivision.actual);
                nodes.push({ type: "subdivision", subdivision, children });
                i += length;
            } else if (i < measure.steps.length) {
                const step = measure.steps[i];
                const hasNote = step.noteStyleId !== undefined;
                const event = hasNote ? eventsByStep[i] : undefined;

                let glyph: INoteGlyph | undefined;
                let beamCount = 0;
                let displayType = NoteDisplayType.Oval;
                let diamondOpen: boolean | undefined;
                let lengthSteps = 1;
                let noteLine: number | undefined;
                let noteStyle: IAudioData | undefined;

                if (hasNote && event) {
                    lengthSteps = Math.max(1, Math.round(
                        event.duration.numerator * measure.meter.stepResolution / event.duration.denominator,
                    ));

                    glyph = this.getStandaloneNoteGlyph(lengthSteps, measure.meter.stepResolution,
                        scoreMetrics.stepsPerPulse, event.duration)
                        ?? { icon: NoteLength.Sixteenth, dotted: false };

                    beamCount = this.glyphBeamCount(glyph.icon);
                    // Each level of subdivision nesting halves the effective note
                    // duration, adding one beam level: root=eighths(1), depth=1→
                    // sixteenths(2), depth=2→thirty-seconds(3), etc.
                    beamCount = Math.max(beamCount, 1 + tupletDepth);

                    if (event.audioData) {
                        noteStyle = event.audioData;
                        displayType = this.resolveDisplayType(event.audioData);
                        diamondOpen = this.resolveDiamondOpen(event.audioData);
                        noteLine = event.audioData.noteLine;
                    }
                }

                nodes.push({
                    type: "step",
                    stepIndex: i,
                    glyph: hasNote ? glyph : undefined,
                    beamCount,
                    displayType,
                    diamondOpen,
                    lengthSteps,
                    noteLine,
                    noteStyle,
                    articulation: hasNote ? step.articulation : undefined,
                });

                // If lengthSteps > 1, the next lengthSteps - 1 steps are occupied by this note's duration tail and
                // cannot have their own note events. Add empty slots for them.
                // Cap to the current recursion level boundary so a long note inside a subdivision does not
                // consume the next array slot that belongs to the parent level.
                const consumed = Math.min(lengthSteps, endIdx - i);
                for (let j = 1; j < consumed; j++) {
                    nodes.push({
                        type: "step",
                        stepIndex: i + j,
                        glyph: undefined,
                        beamCount: 0,
                        displayType: NoteDisplayType.Oval,
                        diamondOpen: undefined,
                        lengthSteps: 1,
                    });
                }

                i += consumed;
            }
        }

        return { nodes, length: i - startIdx };
    }

    /**
     * Marks step indices that are "consumed" by a preceding note's extended duration.
     * Tuplet children reset the count — a note before a tuplet does not bleed inside it.
     *
     * @param nodes The nodes to process.
     *
     * @returns Set of step indices that are occupied by note tails (not available for new notes or rests).
     */
    private computeNoteOccupiedSteps(nodes: IStaffTreeNode[]): Set<number> {
        const occupied = new Set<number>();
        let remaining = 0;

        const walk = (items: IStaffTreeNode[], inTuplet: boolean): void => {
            for (const item of items) {
                if (item.type === "subdivision") {
                    const saved = remaining;
                    remaining = 0;
                    walk(item.children, true);
                    remaining = saved;
                } else if (item.glyph) {
                    remaining = inTuplet ? 0 : item.lengthSteps - 1;
                } else if (remaining > 0) {
                    occupied.add(item.stepIndex);
                    remaining--;
                } else {
                    remaining = 0;
                }
            }
        };

        walk(nodes, false);

        return occupied;
    }

    /**
     * Recursively assigns beam spans. At the top level, beam runs are broken at pulse boundaries;
     * inside tuplets, the entire tuplet is treated as one beam group (no internal pulse breaks).
     *
     * @param nodes The nodes to process.
     * @param noteOccupied Set of step indices occupied by note tails (these do not break beams).
     * @param pulseSize The number of steps per pulse (for pulse-aligned beams).
     * @param usePulseBoundaries Whether to break beam runs at pulse boundaries (true for top level,
     *                           false inside tuplets).
     * @param target Output map of step indices to beam info, which is mutated by this function.
     * @param scopeBeamLevel The beam level corresponding to the current tuplet scope (1 for eighths in top level,
     *                       increases by 1 for each nested tuplet). This is used to preserve inner beams when
     *                       processing parent-level runs.
     */
    private computeBeamSpansForLevel(nodes: IStaffTreeNode[], noteOccupied: Set<number>, pulseSize: number,
        usePulseBoundaries: boolean, target: Map<number, IBeamInfo>, scopeBeamLevel: number): void {
        let run: IStaffStepNode[] = [];
        let basePos = 0;
        const descendantIndices = new Set<number>();
        const descendantNormals = new Map<number, number>();

        // Track subdivisions whose container beam (negative key) needs to be
        // validated after run processing: only keep the beam when the last
        // descendant step actually connects right (shared-right segment).
        const pendingSubdivisionBeams: Array<{ negativeKey: number; lastDescendantStepIndex: number; }> = [];

        const flush = (): void => {
            if (run.length >= 2) {
                this.assignBeamSegments(run, target, descendantIndices, descendantNormals, scopeBeamLevel);
            }

            // After flushing, validate pending subdivision container beams.
            // Only keep them if the last descendant step received a shared-right
            // segment (meaning it connects to a next note outside the subdivision).
            for (const pending of pendingSubdivisionBeams) {
                const lastBeam = target.get(pending.lastDescendantStepIndex);
                const hasRightConnection = lastBeam?.segments.some((s) => {
                    return s.kind === "shared-right" && s.level === 1;
                });

                if (!hasRightConnection) {
                    target.delete(pending.negativeKey);
                }
            }
            pendingSubdivisionBeams.length = 0;

            run = [];
            descendantIndices.clear();
        };

        const pushStep = (step: IStaffStepNode, beamCount: number): void => {
            if (step.glyph && beamCount > 0) {
                run.push({ ...step, beamCount });

                return;
            }

            if (step.glyph || !noteOccupied.has(step.stepIndex)) {
                // Non-beamable note or genuine rest breaks the active run.
                // Note tails (occupied, no glyph) do not break the run.
                flush();
            }
        };

        for (const node of nodes) {
            if (node.type === "subdivision") {
                // First compute inner beams (e.g. secondary beam of inner 16ths).
                this.computeBeamSpansForLevel(node.children, noteOccupied, node.subdivision.actual, false, target,
                    scopeBeamLevel + 1);

                // Then let descendants participate in parent-level beam run.
                // Mark them so assignBeamSegments knows to only compute level 1 (preserve inner beams).
                const descendantSteps = this.collectDescendantSteps(node.children);
                for (const step of descendantSteps) {
                    descendantIndices.add(step.stepIndex);
                    descendantNormals.set(step.stepIndex, node.subdivision.normal);
                    pushStep(step, step.beamCount);
                }

                // Tentatively place a shared-right beam on the subdivision container
                // itself so that width:100% is relative to the full subdivision width,
                // correctly reaching the next note outside. The beam will be validated
                // (and possibly removed) when the run is flushed.
                // extentSteps: beam from container center (left:50%) to next note's center.
                // Container width = normal steps, next note center = normal + 0.5 steps.
                // Distance in container units: (normal * 0.5 + 0.5) / normal = 0.5 + 0.5 / normal.
                if (descendantSteps.length > 0) {
                    const { normal } = node.subdivision;
                    const extentSteps = 0.5 + (0.5 / normal);
                    const negativeKey = -(node.subdivision.id + 1);
                    target.set(negativeKey, {
                        segments: [{ level: 1, kind: "shared-right", extentSteps }],
                    });
                    pendingSubdivisionBeams.push({
                        negativeKey,
                        lastDescendantStepIndex: descendantSteps[descendantSteps.length - 1].stepIndex,
                    });
                }

                if (usePulseBoundaries) {
                    basePos += node.subdivision.normal;
                }
            } else {
                pushStep(node, node.beamCount);
                if (usePulseBoundaries) {
                    basePos++;
                }
            }

            if (usePulseBoundaries && pulseSize > 0 && basePos >= pulseSize) {
                flush();
                basePos %= pulseSize;
            }
        }

        flush();
    }

    private collectDescendantSteps(nodes: IStaffTreeNode[]): IStaffStepNode[] {
        const result: IStaffStepNode[] = [];
        for (const node of nodes) {
            if (node.type === "step") {
                result.push(node);
            } else {
                result.push(...this.collectDescendantSteps(node.children));
            }
        }

        return result;
    }

    private assignBeamSegments(
        run: IStaffStepNode[],
        target: Map<number, IBeamInfo>,
        descendantIndices?: Set<number>,
        descendantNormals?: Map<number, number>,
        scopeBeamLevel = 1,
    ): void {
        const counts = run.map((n) => {
            return n.beamCount;
        });

        for (let i = 0; i < run.length; i++) {
            const segments: IBeamSegment[] = [];
            const isDescendant = descendantIndices?.has(run[i].stepIndex);

            for (let level = 1; level <= counts[i]; level++) {
                // Descendants keep higher levels from deeper scopes.
                // Current scope may only overwrite up to its own beam level.
                if (isDescendant && level > scopeBeamLevel) {
                    continue;
                }

                // Level 1 must remain continuous across tuplets and non-tuplets in the same run.
                let leftHasShared = i > 0 && counts[i - 1] >= level;
                if (leftHasShared) {
                    const leftIsDesc = descendantIndices?.has(run[i - 1].stepIndex);
                    if (leftIsDesc && level > scopeBeamLevel) {
                        leftHasShared = false;
                    }
                }

                let rightHasShared = i + 1 < run.length && counts[i + 1] >= level;
                if (rightHasShared) {
                    const rightIsDesc = descendantIndices?.has(run[i + 1].stepIndex);
                    if (rightIsDesc && level > scopeBeamLevel) {
                        rightHasShared = false;
                    }
                }

                if (rightHasShared) {
                    if (isDescendant) {
                        const nextOutside = i + 1 < run.length
                            && !descendantIndices!.has(run[i + 1].stepIndex);

                        if (nextOutside) {
                            // The run div covers the full subdivision width (flex:1 in flex:N),
                            // so scale the extent so width% × N = actual distance in flex units.
                            const normal = descendantNormals?.get(run[i].stepIndex) ?? 1;
                            const extent = 0.5 + (0.5 / normal);
                            segments.push(
                                { level, kind: "shared-right", extentSteps: extent },
                            );
                        } else {
                            segments.push(
                                { level, kind: "shared-right", extentSteps: run[i].lengthSteps },
                            );
                        }
                    } else {
                        // Non-descendant connecting to a descendant. If the descendant is the last in
                        // its subdivision, extend the beam to the subdivision centre (not the descendant
                        // centre), because the single child is centred in the flex:N container.
                        const nextIsDesc = descendantIndices?.has(run[i + 1].stepIndex);
                        const nextIsLast = nextIsDesc
                            && (i + 2 >= run.length
                                || !descendantIndices!.has(run[i + 2].stepIndex));
                        const normal = nextIsLast
                            ? (descendantNormals?.get(run[i + 1].stepIndex) ?? 1)
                            : 1;
                        const extent = nextIsLast ? 0.5 + (normal / 2) : run[i].lengthSteps;

                        segments.push(
                            { level, kind: "shared-right", extentSteps: extent },
                        );
                    }
                } else if (!leftHasShared) {
                    const partialKind = i === 0 ? "partial-right" : "partial-left";
                    segments.push({ level, kind: partialKind });
                } else if (i === run.length - 1) {
                    // Last note with left connection but no right: needs partial-left to terminate beam.
                    segments.push({ level, kind: "partial-left" });
                }
            }
            if (segments.length > 0) {
                const overwriteLevels = new Set(segments.map((segment) => {
                    return segment.level;
                }));
                const existing = target.get(run[i].stepIndex)?.segments ?? [];
                const kept = existing.filter((segment) => {
                    return !overwriteLevels.has(segment.level);
                });
                target.set(run[i].stepIndex, { segments: [...kept, ...segments] });
            } else if (counts[i] > 0) {
                // Note is in the run but has no segments on its own slot (covered by left-neighbor).
                const existing = target.get(run[i].stepIndex);
                if (!existing) {
                    target.set(run[i].stepIndex, { segments: [] });
                }
            }
        }
    }

    /**
     * Computes bracket/number labels for top-level tuplets. Positions are expressed as percentages
     * of the bar width, matching the flex layout (each regular step = flex:1, tuplet = flex:normal).
     *
     * @param nodes The nodes to process.
     * @param beamSpans Map of step indices to beam info, used to determine whether to show brackets.
     * @param baseSteps The number of base-grid steps in the measure, used to convert from step indices to percentages.
     *
     * @returns List of tuplet labels with position and text info.
     */
    private computeTupletLabels(
        nodes: IStaffTreeNode[],
        beamSpans: Map<number, IBeamInfo>,
        baseSteps: number,
    ): ITupletLabel[] {
        const labels: ITupletLabel[] = [];

        // Compute the base-grid centers of the leftmost and rightmost leaf (step) descendants
        // of an item list, so a tuplet bracket can span the full extent of its content
        // (including any nested tuplets).
        const leafBounds = (items: IStaffTreeNode[], originBase: number,
            baseWidth: number): { first: number; last: number; } => {
            const totalUnits = items.reduce((sum, item) => {
                return sum + (item.type === "subdivision" ? item.subdivision.normal : 1);
            }, 0);
            const unitWidth = totalUnits > 0 ? baseWidth / totalUnits : 0;

            let cursor = originBase;
            let first: number | null = null;
            let last = originBase;
            for (const item of items) {
                const span = item.type === "subdivision" ? item.subdivision.normal : 1;
                const width = unitWidth * span;
                let firstCenter: number;
                let lastCenter: number;
                if (item.type === "subdivision") {
                    const inner = leafBounds(item.children, cursor, width);
                    firstCenter = inner.first;
                    lastCenter = inner.last;
                } else {
                    firstCenter = cursor + (width / 2);
                    lastCenter = firstCenter;
                }

                first ??= firstCenter;
                last = lastCenter;
                cursor += width;
            }

            return { first: first ?? originBase, last };
        };

        // Walk the tree in flex-coordinate space. Each regular step contributes 1 base unit,
        // each tuplet contributes its "normal" base units to the parent's flex span. Inside a
        // tuplet, the children share its base width (= normal) equally regardless of nesting.
        const walk = (items: IStaffTreeNode[], depth: number, originBase: number, baseWidth: number): void => {
            const totalUnits = items.reduce((sum, item) => {
                return sum + (item.type === "subdivision" ? item.subdivision.normal : 1);
            }, 0);
            const unitWidth = totalUnits > 0 ? baseWidth / totalUnits : 0;

            let cursorBase = originBase;
            for (const item of items) {
                if (item.type !== "subdivision") {
                    cursorBase += unitWidth;
                    continue;
                }

                const { actual, normal } = item.subdivision;
                const tupletBaseWidth = unitWidth * normal;

                // Span from the leftmost leaf center to the rightmost leaf center of the
                // subdivision's full subtree (so brackets enclose all nested tuplets too).
                const bounds = leafBounds(item.children, cursorBase, tupletBaseWidth);
                const labelLeftBase = bounds.first;
                const labelWidthBase = bounds.last - bounds.first;

                const hasSiblings = items.length > 1;
                const hasUnbeamedChild = this.tupletHasUnbeamedChild(item, beamSpans);
                const hasDirectRestOrUnbeamed = item.children.some((child) => {
                    if (child.type !== "step") {
                        return false;
                    }

                    return !child.glyph || !beamSpans.has(child.stepIndex);
                });

                // Only real tuplets get bracket/number labels. Non-tuplet subdivisions
                // still create subdivision container nodes for correct beam computation,
                // but are rendered without tuplet notation.
                if (item.subdivision.isTuplet) {
                    labels.push({
                        leftPercent: (labelLeftBase / baseSteps) * 100,
                        widthPercent: (labelWidthBase / baseSteps) * 100,
                        text: actual.toString(),
                        bracket: hasSiblings || hasUnbeamedChild || hasDirectRestOrUnbeamed,
                        placement: depth % 2 === 0 ? "above" : "below",
                    });
                }

                walk(item.children, depth + 1, cursorBase, tupletBaseWidth);
                cursorBase += tupletBaseWidth;
            }
        };

        walk(nodes, 0, 0, baseSteps);

        return labels;
    }

    private tupletHasUnbeamedChild(node: IStaffSubdivisionNode, beamSpans: Map<number, IBeamInfo>): boolean {
        for (const child of node.children) {
            if (child.type === "step") {
                if (!child.glyph || !beamSpans.has(child.stepIndex)) {
                    return true;
                }
            } else {
                if (this.tupletHasUnbeamedChild(child, beamSpans)) {
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * Groups consecutive top-level rest steps into metrically-aligned rest symbols.
     * Tuplet nodes break the rest run; steps inside tuplets are handled individually in the renderer.
     * Uses 0-based base-grid positions for metric alignment (converted from the 1-based original).
     *
     * @param nodes The nodes to process.
     * @param noteOccupied Set of step indices occupied by note tails (these do not count as rests).
     * @param stepsPerBar The number of steps in a bar.
     * @param stepsPerPulse The number of steps in a pulse.
     * @param stepResolution The resolution of a step.
     *
     * @returns Map of step indices to rest group info, keyed by the first step index of each rest group.
     */
    private computeRestGroups(nodes: IStaffTreeNode[], noteOccupied: Set<number>, stepsPerBar: number,
        stepsPerPulse: number, stepResolution: number): Map<number, IRestGroup> {
        const baseCandidates: Array<{ steps: number; icon: NoteLength; }> = [
            { steps: stepResolution, icon: NoteLength.Whole },
            { steps: stepResolution / 2, icon: NoteLength.Half },
            { steps: stepResolution / 4, icon: NoteLength.Quarter },
            { steps: stepResolution / 8, icon: NoteLength.Eighth },
            { steps: stepResolution / 16, icon: NoteLength.Sixteenth },
            { steps: stepResolution / 32, icon: NoteLength.ThirtySecond },
        ];

        const candidates: IRestCandidate[] = [];
        for (const base of baseCandidates) {
            const dottedSteps = base.steps + (base.steps / 2);
            if (Number.isInteger(dottedSteps) && dottedSteps >= 2 && dottedSteps <= stepsPerBar) {
                candidates.push({ steps: dottedSteps, alignmentSteps: base.steps, icon: base.icon, dotted: true });
            }
            if (Number.isInteger(base.steps) && base.steps >= 1 && base.steps <= stepsPerBar) {
                candidates.push({ steps: base.steps, alignmentSteps: base.steps, icon: base.icon, dotted: false });
            }
        }

        candidates.sort((a, b) => {
            return b.steps - a.steps;
        });

        const result = new Map<number, IRestGroup>();
        if (candidates.length === 0) {
            return result;
        }

        interface RestItem { stepIndex: number; basePos: number; }

        const flushRun = (items: RestItem[]): void => {
            let i = 0;
            while (i < items.length) {
                const pos = items[i].basePos; // 0-based base-grid position
                const remaining = items.length - i;
                let chosen: IRestCandidate | undefined;

                for (const candidate of candidates) {
                    if (candidate.steps > remaining) {
                        continue;
                    }

                    const startPulse = Math.floor(pos / stepsPerPulse);
                    const endPulse = Math.floor((pos + candidate.steps - 1) / stepsPerPulse);
                    const insideSinglePulse = startPulse === endPulse;

                    if (insideSinglePulse) {
                        chosen = candidate;
                        break;
                    }

                    if (candidate.dotted) {
                        continue;
                    }

                    if (pos % candidate.alignmentSteps !== 0) {
                        continue;
                    }

                    chosen = candidate;
                    break;
                }

                if (!chosen) {
                    i++;
                    continue;
                }

                result.set(items[i].stepIndex, {
                    startStep: items[i].stepIndex,
                    lengthSteps: chosen.steps,
                    icon: chosen.icon,
                    dotted: chosen.dotted,
                });
                i += chosen.steps;
            }
        };

        let currentRun: RestItem[] = [];
        let basePos = 0;

        for (const node of nodes) {
            if (node.type === "subdivision") {
                // Subdivision nodes break the rest run and advance by their normal count.
                flushRun(currentRun);
                currentRun = [];
                basePos += node.subdivision.normal;
            } else {
                const isNote = node.glyph !== undefined;
                const isOccupied = noteOccupied.has(node.stepIndex);
                if (!isNote && !isOccupied) {
                    currentRun.push({ stepIndex: node.stepIndex, basePos });
                } else {
                    flushRun(currentRun);
                    currentRun = [];
                }
                basePos++;
            }
        }

        flushRun(currentRun);

        return result;
    }

    private nodeHasAnyNote(node: IStaffTreeNode): boolean {
        if (node.type === "step") {
            return node.glyph !== undefined;
        }

        return node.children.some((c) => {
            return this.nodeHasAnyNote(c);
        });
    }

    /**
     * Renders the hierarchical flex tree.
     *  - Regular step nodes: flex:1 (mirrors grid-view "note-viewer" steps)
     *  - Tuplet containers: flex:normal (mirrors grid-view "tuplet" containers)
     * This produces note positions that exactly match the horizontal centers of the grid-view boxes.
     *
     * @param nodes The tree nodes to render at this level.
     * @param allOccupied Set of step indices that are occupied by note tails or rest groups (these render as
     *                    empty slots).
     * @param restGroups Map of step indices to rest group info, keyed by the first step index of each rest group
     *                   (these render as rest symbols).
     * @param beamSpans Map of step indices to beam info (these render with attached beam segments).
     * @param eventsByStep Array indexed by step position, containing the sounding note event for that step
     *                     (or undefined if there is none).
     * @param keyPrefix A prefix for React keys to ensure uniqueness across recursive calls.
     * @param inTuplet Whether the current level is inside a tuplet, which affects rest rendering.
     * @param tupletActual The actual count of the current tuplet, if inside a tuplet (used to determine rest icons);
     *                     undefined at the top level.
     * @param centerLine The centre line index ((maxNoteLine + 1) / 2), used to compute per-note vertical offsets.
     * @param restLineOffset Vertical offset in px for whole/half rests so they sit on the centre line.
     *
     * @returns List of VNodes representing the rendered items at this level.
     */
    private renderItems(nodes: IStaffTreeNode[], allOccupied: Set<number>, restGroups: Map<number, IRestGroup>,
        beamSpans: Map<number, IBeamInfo>, eventsByStep: Array<ISbDmNoteEvent | undefined>,
        keyPrefix: string, inTuplet: boolean, tupletActual: number | undefined, centerLine: number,
        restLineOffset: number): ComponentChild[] {
        const { scoreMetrics } = this.props;

        return nodes.map((node, index) => {
            if (node.type === "subdivision") {
                // Beam connecting this subdivision's last child to the next note
                // outside is stored under a negative key (see computeBeamSpansForLevel).
                const subBeamInfo = beamSpans.get(-(node.subdivision.id + 1));

                return (
                    <div
                        key={`${keyPrefix}subdivision-${index}`}
                        style={{
                            flex: `${node.subdivision.normal} 1 0`,
                            minWidth: 0,
                            display: "flex",
                            alignItems: "center",
                            height: "100%",
                            position: "relative",
                        }}
                    >
                        {this.renderItems(
                            node.children, allOccupied, restGroups, beamSpans, eventsByStep,
                            `${keyPrefix}${index}-`, true, node.subdivision.actual, centerLine,
                            restLineOffset,
                        )}
                        {subBeamInfo ? this.renderBeamSegments(
                            -(node.subdivision.id + 1), subBeamInfo,
                        ) : null}
                    </div>
                );
            }

            const { stepIndex, glyph, displayType, diamondOpen, noteLine, noteStyle, articulation } = node;
            const slotStyle = { flex: "1 1 0", minWidth: 0 };

            if (glyph) {
                const beamInfo = beamSpans.get(stepIndex);

                // Compute vertical offset for this note's staff line.
                const effectiveNoteLine = noteLine ?? 1;
                const lineOffset = (effectiveNoteLine - centerLine) * 10; // 10px = line spacing
                const translateY = `translateY(calc(-18px + ${lineOffset}px))`;

                const hasBeam = beamInfo !== undefined;
                const headType = this.resolveHeadType(displayType);
                const isNonOval = headType !== NoteImageHeadType.Oval;

                // Build head wrapper classes for non-oval heads and decorations.
                const headWrapperClasses = ["staff-note-head"];
                if (isNonOval) {
                    headWrapperClasses.push(this.headTypeClassName(headType));
                }

                const decoClasses = noteStyle ? this.resolveDecorationClasses(noteStyle, articulation) : [];
                headWrapperClasses.push(...decoClasses);

                // All non-beamed notes get a CSS stem (the SVG stem is always hidden).
                const needsCssStem = !hasBeam;

                const event = eventsByStep[stepIndex];

                const runDivProps: Record<string, unknown> = {
                    key: `${keyPrefix}note-${stepIndex}`,
                    className: "staff-note-viewer-run",
                    style: slotStyle,
                    "data-step-index": stepIndex,
                };

                if (event?.id !== undefined) {
                    runDivProps["data-note-id"] = event.id;
                }

                return (
                    <div {...runDivProps}>
                        <span className={headWrapperClasses.join(" ")}>
                            <NoteImage
                                className="staff-note-viewer-note-symbol"
                                kind={NoteKind.Note}
                                value={glyph.icon}
                                style={{
                                    flexShrink: 0,
                                    transform: translateY,
                                }}
                                headType={headType}
                                dotted={glyph.dotted}
                                diamondOpen={diamondOpen}
                                flagCount={hasBeam ? 0 : undefined}
                                hideStem={true}
                                alt=""
                            />
                            {needsCssStem ? (
                                <span
                                    className="staff-note-head-stem"
                                    style={{ height: `calc(33px + ${lineOffset}px)` }}
                                />
                            ) : null}
                            {this.renderNoteDecorations(noteStyle, articulation)}
                            {headType === NoteImageHeadType.Cross ? this.renderCrossHead() : null}
                        </span>
                        {articulation?.accent ? (
                            <span className="staff-note-viewer-accent">&gt;</span>
                        ) : null}
                        {hasBeam ? this.renderBeamSegments(stepIndex, beamInfo) : null}
                        {hasBeam ? this.renderCustomStem(lineOffset, headType) : null}
                    </div>
                );
            }

            if (allOccupied.has(stepIndex)) {
                return (
                    <div key={`${keyPrefix}empty-${stepIndex}`} className="staff-note-viewer-run" style={slotStyle}
                        data-step-index={stepIndex} />
                );
            }

            const restGroup = restGroups.get(stepIndex);
            if (restGroup) {
                const isWholeOrHalf = restGroup.icon === NoteLength.Whole || restGroup.icon === NoteLength.Half;

                return (
                    <div key={`${keyPrefix}rest-${stepIndex}`} className="staff-note-viewer-run" style={slotStyle}
                        data-step-index={stepIndex}>
                        <NoteImage
                            className="staff-note-viewer-rest-symbol"
                            kind={NoteKind.Rest}
                            value={restGroup.icon}
                            style={{
                                flexShrink: 0,
                                ...(isWholeOrHalf ? { transform: `translateY(${restLineOffset}px)` } : {}),
                            }}
                            dotted={restGroup.dotted}
                            alt=""
                        />
                    </div>
                );
            }

            // Single rest: use tuplet-appropriate icon inside tuplets; otherwise derive from step duration.
            const singleRestIcon: NoteLength = inTuplet && tupletActual !== undefined
                ? this.getTupletRestIcon(this.floorPowerOfTwo(tupletActual))
                : (this.getStandaloneNoteGlyph(1, scoreMetrics.stepsPerBar,
                    scoreMetrics.stepsPerPulse,
                    { numerator: 1, denominator: scoreMetrics.stepsPerBar })?.icon ?? NoteLength.Sixteenth);

            return (
                <div key={`${keyPrefix}rest-${stepIndex}`} className="staff-note-viewer-run" style={slotStyle}
                    data-step-index={stepIndex}>
                    <NoteImage
                        className="staff-note-viewer-rest-symbol"
                        kind={NoteKind.Rest}
                        value={singleRestIcon}
                        style={{ flexShrink: 0 }}
                        alt=""
                    />
                </div>
            );
        });
    }

    /**
     * Renders the beam strokes attached to a single note inside a beam group. Shared strokes bridge
     * to the next beam member (extent in slot widths); partial stubs occupy a fixed pixel width.
     *
     * @param stepIndex The step index of the note to render beams for (used for keying and positioning).
     * @param info The beam info for this note, including the segments to render.
     *
     * @returns List of VNodes representing the beam segments attached to this note.
     */
    private renderBeamSegments(stepIndex: number, info: IBeamInfo): VNode[] {
        const beamGap = 6;
        const primaryTopOffset = 38;
        const stemAnchorOffset = 0;
        const partialPixels = 12;

        return info.segments.map((segment) => {
            const top = `calc(50% - ${primaryTopOffset - ((segment.level - 1) * beamGap)}px)`;
            const key = `beam-${stepIndex}-${segment.level}-${segment.kind}`;

            if (segment.kind === "shared-right") {
                const extent = segment.extentSteps ?? 1;

                return (
                    <span
                        key={key}
                        className="staff-note-viewer-beam"
                        style={{
                            top,
                            left: `calc(50% + ${stemAnchorOffset}px)`,
                            width: `${extent * 100}%`,
                        }}
                    />
                );
            }

            if (segment.kind === "partial-right") {
                return (
                    <span
                        key={key}
                        className="staff-note-viewer-beam"
                        style={{
                            top,
                            left: `calc(50% + ${stemAnchorOffset}px)`,
                            width: `${partialPixels}px`,
                        }}
                    />
                );
            }

            // partial-left: beam goes from a note to the left.
            return (
                <span
                    key={key}
                    className="staff-note-viewer-beam"
                    style={{
                        top,
                        right: `calc(50% - ${stemAnchorOffset}px)`,
                        width: `${partialPixels}px`,
                    }}
                />
            );
        });
    }

    /**
     * Renders a CSS stem overlay for beamed notes, replacing the hidden SVG stem.
     * Spans from the note-head connection point to just above the primary beam.
     *
     * @param lineOffset Vertical offset in px for this note's staff line relative to the centre line.
     * @param headType   The note head type, used for per-head-type stem positioning.
     *
     * @returns A VNode representing the custom stem.
     */
    private renderCustomStem(lineOffset: number, headType: NoteImageHeadType): VNode {
        const headClass = headType !== NoteImageHeadType.Oval
            ? `staff-note-viewer-custom-stem--${this.headTypeClassName(headType)}`
            : "";

        return (
            <span
                className={`staff-note-viewer-custom-stem ${headClass}`}
                style={{
                    height: `calc(35px + ${lineOffset}px)`,
                }}
            />
        );
    }

    private renderWholeBarRestSlot(restLineOffset: number): VNode {
        return (
            <div key="rest-whole-bar" className="staff-note-viewer-run" style={{ width: "100%" }}>
                <NoteImage
                    className="staff-note-viewer-rest-symbol"
                    kind={NoteKind.Rest}
                    value={NoteLength.Whole}
                    style={{
                        flexShrink: 0,
                        transform: `translateY(${restLineOffset}px)`,
                    }}
                    alt=""
                />
            </div>
        );
    }

    /**
     * Returns the number of beam strokes implied by a note glyph icon.
     *
     * @param icon The note glyph icon to evaluate.
     *
     * @returns The number of beam strokes (0 for non-beamable notes).
     */
    private glyphBeamCount(icon: NoteLength): number {
        if (icon === NoteLength.Eighth) {
            return 1;
        }

        if (icon === NoteLength.Sixteenth) {
            return 2;
        }

        if (icon === NoteLength.ThirtySecond) {
            return 3;
        }

        return 0;
    }

    private getStandaloneNoteGlyph(lengthSteps: number, stepsPerBar: number, stepsPerPulse: number,
        duration: IFraction): INoteGlyph | undefined {
        if (stepsPerBar <= 0) {
            return undefined;
        }

        if (stepsPerPulse > 0 && stepsPerPulse % 3 === 0 && lengthSteps * 3 === stepsPerPulse
            && duration.numerator * stepsPerBar === duration.denominator) {
            return { icon: NoteLength.Eighth, dotted: false };
        }

        if (duration.denominator > 0 && duration.numerator * 12 === duration.denominator) {
            return { icon: NoteLength.Eighth, dotted: false };
        }

        // Compute note value from the actual duration fraction, not from the
        // rounded lengthSteps (which loses sub-step precision for subdivision notes).
        const units = duration.denominator > 0
            ? (duration.numerator * 32) / duration.denominator
            : (lengthSteps * 32) / stepsPerBar;
        switch (units) {
            case 32: return { icon: NoteLength.Whole, dotted: false };
            case 24: return { icon: NoteLength.Half, dotted: true };
            case 16: return { icon: NoteLength.Half, dotted: false };
            case 12: return { icon: NoteLength.Quarter, dotted: true };
            case 8: return { icon: NoteLength.Quarter, dotted: false };
            case 6: return { icon: NoteLength.Eighth, dotted: true };
            case 4: return { icon: NoteLength.Eighth, dotted: false };
            case 3: return { icon: NoteLength.Sixteenth, dotted: true };
            case 2: return { icon: NoteLength.Sixteenth, dotted: false };
            case 1: return { icon: NoteLength.ThirtySecond, dotted: false };
            default: return undefined;
        }
    }

    private getTupletRestIcon(effectiveStepsPerPulse: number): NoteLength {
        if (effectiveStepsPerPulse <= 2) {
            return NoteLength.Eighth;
        }

        if (effectiveStepsPerPulse <= 4) {
            return NoteLength.Sixteenth;
        }

        return NoteLength.ThirtySecond;
    }

    private resolveDisplayType(noteStyle: IAudioData): NoteDisplayType {
        if ("mainDisplayType" in noteStyle.characteristics) {
            return noteStyle.characteristics.mainDisplayType!;
        }

        return NoteDisplayType.Oval;
    }

    private resolveHeadType(displayType: NoteDisplayType): NoteImageHeadType {
        switch (displayType) {
            case NoteDisplayType.Cross: {
                return NoteImageHeadType.Cross;
            }

            case NoteDisplayType.Diamond: {
                return NoteImageHeadType.Diamond;
            }

            case NoteDisplayType.Square: {
                return NoteImageHeadType.Square;
            }

            case NoteDisplayType.Triangle: {
                return NoteImageHeadType.Triangle;
            }

            case NoteDisplayType.Oval: {
                return NoteImageHeadType.Oval;
            }
        }
    }

    private resolveDiamondOpen(noteStyle: IAudioData): boolean | undefined {
        const characteristics = noteStyle.characteristics;
        if (!("mainDisplayType" in characteristics) || characteristics.mainDisplayType !== NoteDisplayType.Diamond) {
            return undefined;
        }

        return noteStyle.sampleProfile.builtInDamping === Damping.Open;
    }

    /**
     * Maps a NoteImageHeadType to a CSS class name suffix.
     *
     * @param headType The head type to map.
     *
     * @returns The CSS class name suffix (e.g. "square", "cross").
     */
    private headTypeClassName(headType: NoteImageHeadType): string {
        switch (headType) {
            case NoteImageHeadType.Square: {
                return "square";
            }

            case NoteImageHeadType.Triangle: {
                return "triangle";
            }

            case NoteImageHeadType.Cross: {
                return "cross";
            }

            case NoteImageHeadType.Diamond: {
                return "diamond";
            }

            default: {
                return "";
            }
        }
    }

    /**
     * Resolves CSS class names for note decorations based on the play characteristics.
     *
     * @param noteStyle The note style whose characteristics determine the decorations.
     * @param articulation The per-note articulation (damping, accent, ghost).
     *
     * @returns An array of CSS class name suffixes (without the `staff-note-head--` prefix).
     */
    private resolveDecorationClasses(noteStyle: IAudioData, articulation?: INoteArticulation): string[] {
        const { characteristics: c } = noteStyle;
        const classes: string[] = [];

        if (c.excitationMode === ExcitationMode.Struck) {
            if ("stickTechnique" in c && c.stickTechnique !== undefined) {
                switch (c.stickTechnique) {
                    case StickTechnique.PressRoll: {
                        classes.push("press-roll");
                        break;
                    }

                    case StickTechnique.Rim: {
                        classes.push("rim");
                        break;
                    }

                    case StickTechnique.RimShot: {
                        classes.push("rimshot");
                        break;
                    }

                    case StickTechnique.Body: {
                        classes.push("body-stick");
                        break;
                    }

                    case StickTechnique.CrossClick: {
                        classes.push("cross-click");
                        break;
                    }

                    default: {
                        break;
                    }
                }
            } else {
                switch (c.handTechnique) {
                    case HandTechnique.Thumb: {
                        classes.push("thumb");
                        break;
                    }

                    case HandTechnique.Slap: {
                        classes.push("slap");
                        break;
                    }

                    case HandTechnique.Tap: {
                        classes.push("tap");
                        break;
                    }

                    case HandTechnique.TapWithPalm: {
                        classes.push("tap-palm");
                        break;
                    }

                    default: {
                        break;
                    }
                }

                // Hand + Cross display → hollow square around cross (body).
                if (c.mainDisplayType === NoteDisplayType.Cross) {
                    classes.push("body-hand");
                }
            }
        } else if (c.excitationMode === ExcitationMode.Scraped) {
            classes.push("scraped");
        } else if (c.excitationMode === ExcitationMode.Blown) {
            classes.push("blown");
        }

        // Ghost notes: rendered with parentheses, derived from the note's articulation.
        if (articulation?.ghost) {
            classes.push("ghost-note");
        }

        return classes;
    }

    /**
     * Renders additional note decoration elements (e.g. thumb circle, tap triangle inside square).
     * These are absolutely-positioned spans layered over the note head.
     *
     * @param noteStyle The note style whose characteristics determine the decorations.
     * @param articulation The per-note articulation (damping, accent, ghost).
     *
     * @returns An array of VNodes or null if no decorations are needed.
     */
    private renderNoteDecorations(noteStyle: IAudioData | undefined,
        articulation?: INoteArticulation): VNode[] | null {
        if (!noteStyle) {
            return null;
        }

        const { characteristics } = noteStyle;
        const nodes: VNode[] = [];

        if (characteristics.excitationMode === ExcitationMode.Struck && "handTechnique" in characteristics
            && characteristics.handTechnique !== undefined) {
            switch (characteristics.handTechnique) {
                case HandTechnique.Thumb: {
                    nodes.push(
                        <span key="thumb-circle" className="staff-note-head-thumb-circle" />,
                    );
                    break;
                }

                case HandTechnique.Tap:
                case HandTechnique.TapWithPalm: {
                    nodes.push(
                        <span key="tap-triangle" className="staff-note-head-tap-triangle" />,
                    );
                    break;
                }

                case HandTechnique.Slap: {
                    NoteImage.registerSymbol("cross-head", "0 0 14 14",
                        `<line x1="2" y1="2" x2="12" y2="12" />` +
                        `<line x1="12" y1="2" x2="2" y2="12" />`,
                    );

                    nodes.push(
                        <svg key="slap-cross" className="staff-note-head-slap-svg"
                            width={10} height={10}
                            viewBox="0 0 14 14"
                            aria-hidden="true"
                            style={{
                                stroke: "var(--color-base-100)",
                                strokeWidth: 3,
                                strokeLinecap: "round",
                            }}>
                            <use href="#symbol-cross-head" />
                        </svg>,
                    );
                    break;
                }

                default: {
                    break;
                }
            }
        }

        if (characteristics.excitationMode === ExcitationMode.Struck && "stickTechnique" in characteristics
            && characteristics.stickTechnique === StickTechnique.PressRoll) {
            NoteImage.registerSymbol("press-roll", "0 0 14 35",
                `<line x1="12" y1="3" x2="2" y2="8" />` +
                `<line x1="12" y1="9" x2="2" y2="14" />` +
                `<line x1="12" y1="15" x2="2" y2="20" />`,
            );

            nodes.push(
                <svg key="press-roll" className="staff-note-head-press-roll-svg"
                    width={14} height={35}
                    aria-hidden="true"
                    style={{ stroke: "var(--color-base-content)", strokeWidth: 2.5, strokeLinecap: "round" }}>
                    <use href="#symbol-press-roll" />
                </svg>,
            );
        }

        if (characteristics.excitationMode === ExcitationMode.Struck && "stickTechnique" in characteristics
            && characteristics.stickTechnique === StickTechnique.RimShot) {
            NoteImage.registerSymbol("cross-head", "0 0 14 14",
                `<line x1="2" y1="2" x2="12" y2="12" />` +
                `<line x1="12" y1="2" x2="2" y2="12" />`,
            );

            nodes.push(
                <svg key="rimshot-cross" className="staff-note-head-rimshot-cross-svg"
                    width={8} height={8}
                    aria-hidden="true"
                    style={{ stroke: "var(--color-base-content)", strokeWidth: 2.5, strokeLinecap: "round" }}>
                    <use href="#symbol-cross-head" />
                </svg>,
            );
        }

        // Damped (muted) note: plus sign above the note head, derived from the note's articulation.
        if (articulation?.damping === Damping.Muted) {
            nodes.push(
                <span key="damped-plus" className="staff-note-head-damped-plus">+</span>,
            );
        }

        // Ghost note: closing parenthesis (opening is via CSS ::before on .ghost-note).
        if (articulation?.ghost) {
            nodes.push(
                <span key="ghost-paren" className="staff-note-head-ghost-paren">)</span>,
            );
        }

        return nodes.length > 0 ? nodes : null;
    }

    /**
     * Renders the cross (×) note head as a cached SVG symbol with rounded line caps.
     *
     * @returns An SVG VNode referencing the cached cross symbol.
     */
    private renderCrossHead(): VNode {
        NoteImage.registerSymbol("cross-head", "0 0 14 14",
            `<line x1="2" y1="2" x2="12" y2="12" />` +
            `<line x1="12" y1="2" x2="2" y2="12" />`,
        );

        return (
            <svg className="staff-note-head-cross-svg"
                width={14} height={14}
                aria-hidden="true"
                style={{
                    stroke: "var(--color-base-content)",
                    strokeWidth: 2.8,
                    strokeLinecap: "round",
                    overflow: "visible"
                }}>
                <use href="#symbol-cross-head" />
            </svg>
        );
    }

    private isPowerOfTwo(value: number): boolean {
        if (value <= 0 || !Number.isInteger(value)) {
            return false;
        }

        return (value & (value - 1)) === 0;
    }

    private floorPowerOfTwo(value: number): number {
        if (value < 1) {
            return 1;
        }

        let result = 1;
        while (result * 2 <= value) {
            result *= 2;
        }

        return result;
    }
}
