/*
 * Copyright (c) Mike Lischke. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */

export const baseUrl = "https://samba-chemnitz.de/";
export const serialisationVersion = 2;

// ==================================================================
//                            URL Characters
// ==================================================================

// RFC3986 does not explicitly list valid characters, but it does highlight some as reserved/unreserved
// Reserved: general delimiters: :/?#[]@, sub delimiters: !$&'()*+,;=
// Unreserved:  A-Za-z0-9-._~
// Elsewhere, the internet tell us there are some "unwise" characters: {}|\^[]`. We aspire to be wise,
// but may grow dumb later.
// So we stick with the RFC. We use A-Za-Z0-9_~ for encoding beats, and reserve .- for our own syntax.

export const conversionBase = 64n; // 64 characters to safely use in URLs

export const urlNumberToCharacter: Record<number, string> = {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
    10: "a",
    11: "b",
    12: "c",
    13: "d",
    14: "e",
    15: "f",
    16: "g",
    17: "h",
    18: "i",
    19: "j",
    20: "k",
    21: "l",
    22: "m",
    23: "n",
    24: "o",
    25: "p",
    26: "q",
    27: "r",
    28: "s",
    29: "t",
    30: "u",
    31: "v",
    32: "w",
    33: "x",
    34: "y",
    35: "z",
    36: "A",
    37: "B",
    38: "C",
    39: "D",
    40: "E",
    41: "F",
    42: "G",
    43: "H",
    44: "I",
    45: "J",
    46: "K",
    47: "L",
    48: "M",
    49: "N",
    50: "O",
    51: "P",
    52: "Q",
    53: "R",
    54: "S",
    55: "T",
    56: "U",
    57: "V",
    58: "W",
    59: "X",
    60: "Y",
    61: "Z",
    62: "~",
    63: "_"
};

export const urlCharacterToNumber: Record<string, bigint> = {
    "0": 0n,
    "1": 1n,
    "2": 2n,
    "3": 3n,
    "4": 4n,
    "5": 5n,
    "6": 6n,
    "7": 7n,
    "8": 8n,
    "9": 9n,
    "a": 10n,
    "b": 11n,
    "c": 12n,
    "d": 13n,
    "e": 14n,
    "f": 15n,
    "g": 16n,
    "h": 17n,
    "i": 18n,
    "j": 19n,
    "k": 20n,
    "l": 21n,
    "m": 22n,
    "n": 23n,
    "o": 24n,
    "p": 25n,
    "q": 26n,
    "r": 27n,
    "s": 28n,
    "t": 29n,
    "u": 30n,
    "v": 31n,
    "w": 32n,
    "x": 33n,
    "y": 34n,
    "z": 35n,
    "A": 36n,
    "B": 37n,
    "C": 38n,
    "D": 39n,
    "E": 40n,
    "F": 41n,
    "G": 42n,
    "H": 43n,
    "I": 44n,
    "J": 45n,
    "K": 46n,
    "L": 47n,
    "M": 48n,
    "N": 49n,
    "O": 50n,
    "P": 51n,
    "Q": 52n,
    "R": 53n,
    "S": 54n,
    "T": 55n,
    "U": 56n,
    "V": 57n,
    "W": 58n,
    "X": 59n,
    "Y": 60n,
    "Z": 61n,
    "~": 62n,
    "_": 63n
};

export const polyrhythmNumberToCharacter: Record<number, string> = {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
    10: "-"
};

export const polyrhythmCharacterToNumber: Record<string, bigint> = {
    "0": 0n,
    "1": 1n,
    "2": 2n,
    "3": 3n,
    "4": 4n,
    "5": 5n,
    "6": 6n,
    "7": 7n,
    "8": 8n,
    "9": 9n,
    "-": 10n
};
