/*
 * Copyright (c) Mike Lischke. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */

import {
    mdiAccountGroupOutline,
    mdiAccountOutline,
    mdiAlertCircleOutline,
    mdiAlertOutline,
    mdiArrowDown,
    mdiArrowLeft,
    mdiArrowRight,
    mdiArrowUp,
    mdiBellBadgeOutline,
    mdiBellCancelOutline,
    mdiBellOffOutline,
    mdiBellOutline,
    mdiBookOutline,
    mdiBookmarkOutline,
    mdiBookshelf,
    mdiBriefcaseOutline,
    mdiBugOutline,
    mdiCalendarOutline,
    mdiCheck,
    mdiCheckAll,
    mdiChevronDown,
    mdiChevronLeft,
    mdiChevronRight,
    mdiChevronUp,
    mdiClockOutline,
    mdiClose,
    mdiCloseBoxMultipleOutline,
    mdiCloudDownloadOutline,
    mdiCloudOutline,
    mdiCloudUploadOutline,
    mdiCodeTags,
    mdiCog,
    mdiCogOutline,
    mdiConsole,
    mdiContentCopy,
    mdiContentSaveOutline,
    mdiCreditCardOutline,
    mdiDatabaseOutline,
    mdiDeleteOutline,
    mdiDotsHorizontal,
    mdiDotsVertical,
    mdiDownloadOutline,
    mdiEmailOutline,
    mdiExportVariant,
    mdiEyeOffOutline,
    mdiEyeOutline,
    mdiFileDocumentOutline,
    mdiFileOutline,
    mdiFilePdfBox,
    mdiFilePlusOutline,
    mdiFilterOutline,
    mdiFire,
    mdiFolderOpenOutline,
    mdiFolderOutline,
    mdiFolderPlusOutline,
    mdiFormatBold,
    mdiFormatItalic,
    mdiFormatListBulleted,
    mdiFormatListNumbered,
    mdiFullscreen,
    mdiFullscreenExit,
    mdiHeartOutline,
    mdiHelpCircleOutline,
    mdiHistory,
    mdiHomeOutline,
    mdiInboxOutline,
    mdiInformationOutline,
    mdiKeyOutline,
    mdiLightbulbOutline,
    mdiLink,
    mdiLockOpenOutline,
    mdiLockOutline,
    mdiLogin,
    mdiLogout,
    mdiMagnify,
    mdiMagnifyMinus,
    mdiMagnifyPlus,
    mdiMenu,
    mdiMinus,
    mdiMusic,
    mdiNoteOutline,
    mdiPencilOutline,
    mdiPin,
    mdiPinOutline,
    mdiPlay,
    mdiPlayCircleOutline,
    mdiPlaylistRemove,
    mdiPlus,
    mdiPulse,
    mdiRedo,
    mdiRefresh,
    mdiReplyOutline,
    mdiRocketLaunchOutline,
    mdiServer,
    mdiShieldOutline,
    mdiStar,
    mdiStarOutline,
    mdiStop,
    mdiStopCircleOutline,
    mdiSync,
    mdiTagOutline,
    mdiThumbDownOutline,
    mdiThumbUpOutline,
    mdiTools,
    mdiTriangleDown,
    mdiUndo,
    mdiUnfoldLessHorizontal,
    mdiUnfoldMoreHorizontal,
    mdiVolumeHigh,
    mdiVolumeOff,
    mdiWeb,
    mdiWindowMaximize,
} from "@mdi/js";

/** Material Design Icons available for use in the UI. Only icons with valid MDI mappings are included. */
export enum UIIcon {
    Undefined,
    Account,
    Add,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Bell,
    BellDot,
    BellSlash,
    BellSlashDot,
    Bold,
    Book,
    Bookmark,
    Briefcase,
    Bug,
    Calendar,
    Check,
    CheckAll,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChromeClose,
    ClearAll,
    Clock,
    Close,
    CloseAll,
    Cloud,
    CloudDownload,
    Code,
    CollapseAll,
    Copy,
    CreditCard,
    Database,
    Discard,
    Download,
    Edit,
    Ellipsis,
    Error,
    ExpandAll,
    Export,
    Eye,
    EyeClosed,
    File,
    FilePdf,
    FileText,
    Filter,
    Flame,
    Folder,
    FolderOpened,
    Gear,
    Globe,
    Heart,
    History,
    Home,
    HorizontalRule,
    Inbox,
    Info,
    Italic,
    KebabVertical,
    Key,
    Library,
    Lightbulb,
    Link,
    ListOrdered,
    ListUnordered,
    Lock,
    Mail,
    Menu,
    Music,
    Mute,
    NewFile,
    NewFolder,
    Note,
    Organization,
    Pencil,
    Pin,
    Pinned,
    Play,
    Pulse,
    Question,
    Redo,
    Refresh,
    Rename,
    Reply,
    Rocket,
    Run,
    Save,
    ScreenFull,
    ScreenNormal,
    Search,
    Server,
    Settings,
    Shield,
    SignIn,
    SignOut,
    Star,
    StarEmpty,
    StarFull,
    Stop,
    StopCircle,
    Sync,
    Tag,
    Terminal,
    Thumbsdown,
    Thumbsup,
    Tools,
    Trash,
    Trashcan,
    TriangleDown,
    Unlock,
    Unmute,
    Upload,
    VmRunning,
    Warning,
    Window,
    ZoomIn,
    ZoomOut,
}

/** Maps UIIcon enum members to Material Design Icon SVG path strings (outline variants preferred). */
export const uiIconToMdiMap = new Map<UIIcon, string>([
    [UIIcon.Account, mdiAccountOutline],
    [UIIcon.Add, mdiPlus],
    [UIIcon.ArrowDown, mdiArrowDown],
    [UIIcon.ArrowLeft, mdiArrowLeft],
    [UIIcon.ArrowRight, mdiArrowRight],
    [UIIcon.ArrowUp, mdiArrowUp],
    [UIIcon.Bell, mdiBellOutline],
    [UIIcon.BellDot, mdiBellBadgeOutline],
    [UIIcon.BellSlash, mdiBellOffOutline],
    [UIIcon.BellSlashDot, mdiBellCancelOutline],
    [UIIcon.Bold, mdiFormatBold],
    [UIIcon.Book, mdiBookOutline],
    [UIIcon.Bookmark, mdiBookmarkOutline],
    [UIIcon.Briefcase, mdiBriefcaseOutline],
    [UIIcon.Bug, mdiBugOutline],
    [UIIcon.Calendar, mdiCalendarOutline],
    [UIIcon.Check, mdiCheck],
    [UIIcon.CheckAll, mdiCheckAll],
    [UIIcon.ChevronDown, mdiChevronDown],
    [UIIcon.ChevronLeft, mdiChevronLeft],
    [UIIcon.ChevronRight, mdiChevronRight],
    [UIIcon.ChevronUp, mdiChevronUp],
    [UIIcon.ChromeClose, mdiClose],
    [UIIcon.ClearAll, mdiPlaylistRemove],
    [UIIcon.Clock, mdiClockOutline],
    [UIIcon.Close, mdiClose],
    [UIIcon.CloseAll, mdiCloseBoxMultipleOutline],
    [UIIcon.Cloud, mdiCloudOutline],
    [UIIcon.CloudDownload, mdiCloudDownloadOutline],
    [UIIcon.Code, mdiCodeTags],
    [UIIcon.CollapseAll, mdiUnfoldLessHorizontal],
    [UIIcon.Copy, mdiContentCopy],
    [UIIcon.CreditCard, mdiCreditCardOutline],
    [UIIcon.Database, mdiDatabaseOutline],
    [UIIcon.Discard, mdiUndo],
    [UIIcon.Download, mdiDownloadOutline],
    [UIIcon.Edit, mdiPencilOutline],
    [UIIcon.Ellipsis, mdiDotsHorizontal],
    [UIIcon.Error, mdiAlertCircleOutline],
    [UIIcon.ExpandAll, mdiUnfoldMoreHorizontal],
    [UIIcon.Export, mdiExportVariant],
    [UIIcon.Eye, mdiEyeOutline],
    [UIIcon.EyeClosed, mdiEyeOffOutline],
    [UIIcon.File, mdiFileOutline],
    [UIIcon.FilePdf, mdiFilePdfBox],
    [UIIcon.FileText, mdiFileDocumentOutline],
    [UIIcon.Filter, mdiFilterOutline],
    [UIIcon.Flame, mdiFire],
    [UIIcon.Folder, mdiFolderOutline],
    [UIIcon.FolderOpened, mdiFolderOpenOutline],
    [UIIcon.Gear, mdiCog],
    [UIIcon.Globe, mdiWeb],
    [UIIcon.Heart, mdiHeartOutline],
    [UIIcon.History, mdiHistory],
    [UIIcon.Home, mdiHomeOutline],
    [UIIcon.HorizontalRule, mdiMinus],
    [UIIcon.Inbox, mdiInboxOutline],
    [UIIcon.Info, mdiInformationOutline],
    [UIIcon.Italic, mdiFormatItalic],
    [UIIcon.KebabVertical, mdiDotsVertical],
    [UIIcon.Key, mdiKeyOutline],
    [UIIcon.Library, mdiBookshelf],
    [UIIcon.Lightbulb, mdiLightbulbOutline],
    [UIIcon.Link, mdiLink],
    [UIIcon.ListOrdered, mdiFormatListNumbered],
    [UIIcon.ListUnordered, mdiFormatListBulleted],
    [UIIcon.Lock, mdiLockOutline],
    [UIIcon.Mail, mdiEmailOutline],
    [UIIcon.Menu, mdiMenu],
    [UIIcon.Music, mdiMusic],
    [UIIcon.Mute, mdiVolumeOff],
    [UIIcon.NewFile, mdiFilePlusOutline],
    [UIIcon.NewFolder, mdiFolderPlusOutline],
    [UIIcon.Note, mdiNoteOutline],
    [UIIcon.Organization, mdiAccountGroupOutline],
    [UIIcon.Pencil, mdiPencilOutline],
    [UIIcon.Pin, mdiPinOutline],
    [UIIcon.Pinned, mdiPin],
    [UIIcon.Play, mdiPlay],
    [UIIcon.Pulse, mdiPulse],
    [UIIcon.Question, mdiHelpCircleOutline],
    [UIIcon.Redo, mdiRedo],
    [UIIcon.Refresh, mdiRefresh],
    [UIIcon.Rename, mdiPencilOutline],
    [UIIcon.Reply, mdiReplyOutline],
    [UIIcon.Rocket, mdiRocketLaunchOutline],
    [UIIcon.Run, mdiPlay],
    [UIIcon.Save, mdiContentSaveOutline],
    [UIIcon.ScreenFull, mdiFullscreen],
    [UIIcon.ScreenNormal, mdiFullscreenExit],
    [UIIcon.Search, mdiMagnify],
    [UIIcon.Server, mdiServer],
    [UIIcon.Settings, mdiCogOutline],
    [UIIcon.Shield, mdiShieldOutline],
    [UIIcon.SignIn, mdiLogin],
    [UIIcon.SignOut, mdiLogout],
    [UIIcon.Star, mdiStarOutline],
    [UIIcon.StarEmpty, mdiStarOutline],
    [UIIcon.StarFull, mdiStar],
    [UIIcon.Stop, mdiStop],
    [UIIcon.StopCircle, mdiStopCircleOutline],
    [UIIcon.Sync, mdiSync],
    [UIIcon.Tag, mdiTagOutline],
    [UIIcon.Terminal, mdiConsole],
    [UIIcon.Thumbsdown, mdiThumbDownOutline],
    [UIIcon.Thumbsup, mdiThumbUpOutline],
    [UIIcon.Tools, mdiTools],
    [UIIcon.Trash, mdiDeleteOutline],
    [UIIcon.Trashcan, mdiDeleteOutline],
    [UIIcon.TriangleDown, mdiTriangleDown],
    [UIIcon.Undefined, ""],
    [UIIcon.Unlock, mdiLockOpenOutline],
    [UIIcon.Unmute, mdiVolumeHigh],
    [UIIcon.Upload, mdiCloudUploadOutline],
    [UIIcon.VmRunning, mdiPlayCircleOutline],
    [UIIcon.Warning, mdiAlertOutline],
    [UIIcon.Window, mdiWindowMaximize],
    [UIIcon.ZoomIn, mdiMagnifyPlus],
    [UIIcon.ZoomOut, mdiMagnifyMinus],
]);

/** Maps kebab-case icon names (e.g. "chevron-down") to UIIcon enum members, for text-embedded icon syntax. */
export const iconNameToUIIcon = new Map<string, UIIcon>(
    Object.keys(UIIcon)
        .filter((key) => {
            return Number.isNaN(Number(key));
        })
        .map((key) => {
            const kebabName = key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

            return [kebabName, UIIcon[key as keyof typeof UIIcon]];
        }),
);
